name: 'Build & Test'

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  linux:
    name: "linux Perl v${{ matrix.perl-version }}"
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
          - "5.10"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1.3
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test

  ubuntu-latest:
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1.3
        with:
          cpanfile: "cpanfile"
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test

###
### Windows and Linux testing
###

  # build:
  #   name: Build distribution
  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 1
  #   container:
  #     image: perldocker/perl-tester:5.30
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Get latest author bundle
  #       run: >
  #         cpm install -g
  #         --show-build-log-on-failure
  #         Dist::Zilla::PluginBundle::Author::OALDERS
  #     - name: Install author deps
  #       run: dzil authordeps | xargs cpm install -g --show-build-log-on-failure
  #     - name: Build
  #       run: dzil build --no-tgz --in dzil_build_dir
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: build_dir
  #         path: dzil_build_dir
  #     - name: Install deps
  #       if: success()
  #       run: >
  #         cd dzil_build_dir
  #         && cpm install -g
  #         --cpanfile cpanfile
  #         --with-develop
  #         --with-suggests
  #         --show-build-log-on-failure
      # - name: Run Tests with coverage
      #   if: success()
      #   env:
      #     AUTHOR_TESTING: 1
      #     CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      #     HARNESS_PERL_SWITCHES: "-MDevel::Cover=+ignore,^local/|^t/|^xt"
      #     RELEASE_TESTING: 1
      #   run: >
      #     cpm install -g
      #     --show-build-log-on-failure
      #     Devel::Cover::Report::Codecov &&
      #     cd dzil_build_dir
      #     && prove -lr --jobs 2 t xt
      #     && cover -report codecov

  macos:
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        perl-version:
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
          - "5.10"
    needs: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1.3.0
        with:
          perl-version: ${{ matrix.perl-version }}
      # - uses: actions/download-artifact@master
      #   with:
      #     name: build_dir
      #     path: .
      - run: perl -V
      #- run: cpanm --installdeps .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: makeqqq
        run: make
      - name: Run Tests
        run: make test
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1        

  windows:
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        perl-version:
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20.3"
          - "5.18.4"
          - "5.16.3"
          - "5.14.4"
          - "5.12.5"
          - "5.10.1"
    needs: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1.3.0
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: makeqqq
        run: make
      - name: Run Tests
        run: make test
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1        

